name: live_cell
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  live_cells_core: ^1.2.1
  collection: ^1.18.0
  code_builder: ^4.10.1
  dart_style: ^2.3.8
  args: ^2.7.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

  build_runner:
  live_cell_extension: 0.6.2
