import 'package:code_builder/code_builder.dart';

import '../../builder/index.dart';
import 'dart_compiler.dart';

/// Compiles [StatementSpec]s to Dart [Expression]s.
class DartStatementCompiler {
  /// The [ValueSpec] to Dart [Expression] compiler
  final DartCompiler compiler;

  DartStatementCompiler({
    required this.compiler
  });

  /// Generate a list of Dart [Expression] implementing a given statement [spec].
  ///
  /// [result] is the name of the variable in which to store the result of the
  /// statement. If this is not null, a variable declaration with the given
  /// name is generated and assigned to the result of the statement.
  Iterable<Expression> compile(StatementSpec spec, {
    String? result
  }) sync* {

    switch (spec) {
      case AssignStatement(
        :final cell,
        :final value
      ):
        yield* _makeAssign(
            cell: cell.get,
            value: value,
            result: result
        );

      case BlockStatement(:final statements):
        final last = statements.length - 1;
        var i = 0;

        for (final statement in statements) {
          yield* compile(statement,
            result: i == last ? result : null
          );

          i++;
        }

      case ExpressionStatement(:final expression):
        if (result != null) {
          yield declareFinal(result)
              .assign(compiler.compile(expression));
        }
    }
  }

  // Private

  /// Temporary variable counter
  var _varCounter = 0;

  /// Generate a new temporary variable name
  String _genSym([String prefix = 'g']) =>
      '$prefix${_varCounter++}';

  /// Generate the list of expressions implementing up an assign statement.
  ///
  /// A variable declaration is emitted that stores the resulting [value] in,
  /// the variable named by [result]. If [result] is null, a new variable name
  /// is generated by [_genSym].
  Iterable<Expression> _makeAssign({
    required CellSpec cell,
    required StatementSpec value,
    required String? result
  }) sync* {
    result ??= _genSym();

    yield* compile(value, result: result);

    yield compiler.compileRef(cell)
        .assign(refer(result));
  }
}